version: "3"
services:
  nginx:
    ports:
      - "80:80"

  nodejs:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node backend/server.js