version: "3"
services:
  nginx:
    ports:
      - "80:80"

  nodejs:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    command: node backend/server.js